package com.example.ui

object LocalizationHelper {
    private val en = mapOf(
        "app_tagline" to "Connecting Cambodia's Farmers and Buyers Directly",
        "home" to "Home",
        "marketplace" to "Marketplace",
        "requests" to "Requests",
        "messages" to "Messages",
        "profile" to "Profile",
        "featured_products" to "Featured Products",
        "featured_requests" to "Featured Requests",
        "recommended_matches" to "Recommended Matches",
        "nearby_opportunities" to "Nearby Map Discovery",
        "market_updates" to "Market Intelligence Hub",
        "ai_price_intel" to "AI price analyzer reports are currently active.",
        "search_hint" to "Search crops, grains, vegetables...",
        "quantity" to "Quantity",
        "grade" to "Quality Grade",
        "price" to "Price",
        "harvest_date" to "Harvest Date",
        "contact_seller" to "Contact Seller",
        "send_offer" to "Send Offer",
        "chat_seller" to "Chat Seller",
        "call_seller" to "Direct Call",
        "chat_buyer" to "Chat Buyer",
        "call_buyer" to "Call Buyer",
        "negotiations" to "Open Negotiations & Contracts",
        "my_wallet" to "My Profile Balance",
        "top_up" to "Deposit Funds",
        "create_listing" to "List Farm Products",
        "create_request" to "Post Buy Request",
        "categories" to "Agricultural Categories",
        "role" to "Account Role",
        "verified" to "Verified AgriPartner",
        "location" to "Location",
        "farmer" to "Farmer (Producer)",
        "buyer" to "Buyer (Trader)",
        "admin" to "Administrator",
        "status" to "Listing Status",
        "about_crop" to "Crop Description & Certified Moister",
        "switch_role_alert" to "Switching simulated account profile...",
        "ai_translate" to "Gemini Dual-Translate",
        "ai_advisor" to "Gemini Price Adviser",
        "ai_tactics" to "Gemini Deal Bargainer",
        "offers_received" to "My Received Offers",
        "incoming" to "Incoming Requests",
        "outgoing" to "My Placed Bids",
        "accept" to "Accept Offer",
        "reject" to "Decline",
        "pending" to "Pending Review",
        "accepted" to "Deal Accepted",
        "rejected" to "Offer Declined",
        "negotiation_helper" to "Bargaining Helper (Gemini AI)",
        "all" to "All",
        "rice" to "Rice",
        "corn" to "Corn",
        "cassava" to "Cassava",
        "vegetables" to "Vegetables",
        "fruits" to "Fruits",
        "beans" to "Beans",
        "peanuts" to "Peanuts",
        "pepper" to "Pepper",
        "rubber" to "Rubber",
        "feed" to "Livestock Feed",
        "other" to "Other Crops",
        "notifications" to "Notifications Centre",
        "no_notif" to "No notifications found.",
        "notif_cleared" to "All indicators cleared.",
        "deadline" to "Purchase Deadline",
        "promo_listing" to "Premium Promote listing ($10)"
    )

    private val km = mapOf(
        "app_tagline" to "ភ្ជាប់ទំនាក់ទំនងកសិករ និងអ្នកទិញនៅកម្ពុជាដោយផ្ទាល់",
        "home" to "ទំព័រដើម",
        "marketplace" to "ផ្សារកសិផល",
        "requests" to "តម្រូវការទិញ",
        "messages" to "សារពិភាក្សា",
        "profile" to "គណនី",
        "featured_products" to "កសិផលលេចធ្លោ",
        "featured_requests" to "តម្រូវការលេចធ្លោ",
        "recommended_matches" to "ការណែនាំពិសេស",
        "nearby_opportunities" to "ស្វែងរកផែនទីក្បែរៗ",
        "market_updates" to "ព័ត៌មានតម្លៃទីផ្សារ",
        "ai_price_intel" to "របាយការណ៍វិភាគតម្លៃដោយប្រព័ន្ធ AI។",
        "search_hint" to "ស្វែងរក កសិផល គ្រាប់ធញ្ញជាតិ បន្លែ...",
        "quantity" to "បរិមាណ",
        "grade" to "កម្រិតគុណភាព",
        "price" to "តម្លៃ",
        "harvest_date" to "ថ្ងៃប្រមូលផល",
        "contact_seller" to "ទាក់ទងអ្នកលក់",
        "send_offer" to "ផ្ញើការចរចា",
        "chat_seller" to "ឆាតជាមួយអ្នកលក់",
        "call_seller" to "តេផ្ទាល់",
        "chat_buyer" to "ឆាតជាមួយអ្នកទិញ",
        "call_buyer" to "តេទៅអ្នកទិញ",
        "negotiations" to "កិច្ចសន្យា និងការចរចា",
        "my_wallet" to "សមតុល្យកាបូបលុយ",
        "top_up" to "បញ្ចូលថវិកា",
        "create_listing" to "បង្ហោះលក់កសិផល",
        "create_request" to "បង្ហោះតម្រូវការទិញ",
        "categories" to "ប្រភេទកសិកម្ម",
        "role" to "តួនាទីគណនី",
        "verified" to "ដៃគូកសិកម្មផ្ទៀងផ្ទាត់",
        "location" to "ទីតាំង",
        "farmer" to "កសិករ (អ្នកផលិត)",
        "buyer" to "អ្នកទិញ (អាជីវករ)",
        "admin" to "អ្នកគ្រប់គ្រង",
        "status" to "ស្ថានភាពលក់",
        "about_crop" to "ការពិពណ៌នាកសិផល និងកម្រិតសំណើម",
        "switch_role_alert" to "កំពុងប្តូរគណនីសាកល្បង...",
        "ai_translate" to "Gemini បកប្រែភាសា",
        "ai_advisor" to "Gemini វិភាគតម្លៃទីផ្សារ",
        "ai_tactics" to "Gemini យុទ្ធសាស្ត្រចរចា",
        "offers_received" to "សំណើទទួលបាន",
        "incoming" to "សំណើចូល",
        "outgoing" to "សំណើប្រជែងតម្លៃរបស់អ្នក",
        "accept" to "យល់ព្រមលើសំណើ",
        "reject" to "បដិសេធ",
        "pending" to "កំពុងពិនិត្យ",
        "accepted" to "ព្រមព្រៀងគ្នាហើយ",
        "rejected" to "បានបដិសេធ",
        "negotiation_helper" to "ជំនួយការចរចា (Gemini AI)",
        "all" to "ទាំងអស់",
        "rice" to "ស្រូវ-អង្ករ",
        "corn" to "ពោត",
        "cassava" to "ដំឡូងមី",
        "vegetables" to "បន្លែបង្ការ",
        "fruits" to "ផ្លែឈើ",
        "beans" to "សណ្តែក",
        "peanuts" to "សណ្តែកដី",
        "pepper" to "ម្រេច",
        "rubber" to "កៅស៊ូ",
        "feed" to "ចំណីសត្វ",
        "other" to "ដំណាំផ្សេងទៀត",
        "notifications" to "មជ្ឈមណ្ឌលដំណឹង",
        "no_notif" to "មិនទាន់មានសេចក្តីជូនដំណឹងទេ។",
        "notif_cleared" to "បានសម្អាតដំណឹងទាំងអស់។",
        "deadline" to "ថ្ងៃឱសានវាទទិញ",
        "promo_listing" to "ផ្សព្វផ្សាយលេចធ្លោ ($១០)"
    )

    fun t(key: String, isKhmer: Boolean): String {
        return if (isKhmer) {
            km[key] ?: en[key] ?: key
        } else {
            en[key] ?: key
        }
    }
}
